"use strict";

// Local data (SBA: array of objects)
// Note: Load this file BEFORE scripts/script.js in index.html
const deals = [
  {
    id: "deal-1",
    restaurant: "Slice City",
    dealName: "2 Slices + Soda",
    price: 7.99,
    type: "Lunch",
    rating: 4.3,
    city: "Newark",
    tags: ["quick", "value", "soda"],
    url: "https://example.com/slice-city",
    image: "https://placehold.co/600x400?text=Slice+City",
  },
  {
    id: "deal-2",
    restaurant: "Mama Mia Pizza",
    dealName: "Large 1-Topping",
    price: 13.99,
    type: "Carryout",
    rating: 4.1,
    city: "Jersey City",
    tags: ["family", "classic", "topping"],
    url: "https://example.com/mama-mia",
    image: "https://placehold.co/600x400?text=Mama+Mia",
  },
  {
    id: "deal-3",
    restaurant: "Downtown Pies",
    dealName: "Family Combo",
    price: 24.99,
    type: "Delivery",
    rating: 4.6,
    city: "Hoboken",
    tags: ["family", "combo", "delivery"],
    url: "https://example.com/downtown-pies",
    image: "https://placehold.co/600x400?text=Downtown+Pies",
  },

  // -------- Added deals --------
  {
    id: "deal-4",
    restaurant: "Brooklyn Brick Oven",
    dealName: "Margherita Slice Trio",
    price: 8.49,
    type: "Lunch",
    rating: 4.4,
    city: "Brooklyn",
    tags: ["margherita", "quick", "classic"],
    url: "https://example.com/brooklyn-brick-oven",
    image: "https://placehold.co/600x400?text=Brooklyn+Brick+Oven",
  },
  {
    id: "deal-5",
    restaurant: "Garden State Pizza",
    dealName: "Medium 2-Topping Special",
    price: 15.99,
    type: "Carryout",
    rating: 4.2,
    city: "Newark",
    tags: ["topping", "value", "share"],
    url: "https://example.com/garden-state-pizza",
    image: "https://placehold.co/600x400?text=Garden+State+Pizza",
  },
  {
    id: "deal-6",
    restaurant: "Hoboken Thin Crust",
    dealName: "Slice + Garlic Knots",
    price: 6.99,
    type: "Lunch",
    rating: 4.0,
    city: "Hoboken",
    tags: ["thin-crust", "knots", "quick"],
    url: "https://example.com/hoboken-thin-crust",
    image: "https://placehold.co/600x400?text=Hoboken+Thin+Crust",
  },
  {
    id: "deal-7",
    restaurant: "Newark Night Pies",
    dealName: "Late Night Large Pie",
    price: 19.99,
    type: "Delivery",
    rating: 4.1,
    city: "Newark",
    tags: ["late-night", "large", "delivery"],
    url: "https://example.com/newark-night-pies",
    image: "https://placehold.co/600x400?text=Newark+Night+Pies",
  },
  {
    id: "deal-8",
    restaurant: "Pepperoni Palace",
    dealName: "Pepperoni Lovers Combo",
    price: 26.49,
    type: "Delivery",
    rating: 4.5,
    city: "Jersey City",
    tags: ["pepperoni", "combo", "fan-favorite"],
    url: "https://example.com/pepperoni-palace",
    image: "https://placehold.co/600x400?text=Pepperoni+Palace",
  },
  {
    id: "deal-9",
    restaurant: "Union Square Pizza Bar",
    dealName: "Personal Pie + Drink",
    price: 10.49,
    type: "Lunch",
    rating: 4.3,
    city: "Manhattan",
    tags: ["personal", "drink", "quick"],
    url: "https://example.com/union-square-pizza-bar",
    image: "https://placehold.co/600x400?text=Union+Square+Pizza+Bar",
  },
  {
    id: "deal-10",
    restaurant: "Jersey Shore Slices",
    dealName: "2 Pies Bundle",
    price: 29.99,
    type: "Carryout",
    rating: 4.0,
    city: "Elizabeth",
    tags: ["bundle", "family", "value"],
    url: "https://example.com/jersey-shore-slices",
    image: "https://placehold.co/600x400?text=Jersey+Shore+Slices",
  },
  {
    id: "deal-11",
    restaurant: "Maplewood Mozza",
    dealName: "Cheese Pie Tuesday",
    price: 12.99,
    type: "Carryout",
    rating: 4.4,
    city: "Maplewood",
    tags: ["cheese", "weekly-special", "classic"],
    url: "https://example.com/maplewood-mozza",
    image: "https://placehold.co/600x400?text=Maplewood+Mozza",
  },
  {
    id: "deal-12",
    restaurant: "Ironbound Italian Kitchen",
    dealName: "Pizza + Pasta Family Combo",
    price: 34.99,
    type: "Delivery",
    rating: 4.6,
    city: "Newark",
    tags: ["family", "pasta", "combo"],
    url: "https://example.com/ironbound-italian-kitchen",
    image: "https://placehold.co/600x400?text=Ironbound+Italian+Kitchen",
  },
  {
    id: "deal-13",
    restaurant: "Clifton Crispy Crust",
    dealName: "Thin Crust Duo Deal",
    price: 18.99,
    type: "Carryout",
    rating: 4.2,
    city: "Clifton",
    tags: ["thin-crust", "duo", "value"],
    url: "https://example.com/clifton-crispy-crust",
    image: "https://placehold.co/600x400?text=Clifton+Crispy+Crust",
  },
  {
    id: "deal-14",
    restaurant: "Ridgewood Wood-Fired",
    dealName: "Wood-Fired Special",
    price: 27.99,
    type: "Delivery",
    rating: 4.5,
    city: "Ridgewood",
    tags: ["wood-fired", "premium", "fan-favorite"],
    url: "https://example.com/ridgewood-wood-fired",
    image: "https://placehold.co/600x400?text=Ridgewood+Wood-Fired",
  },
  {
    id: "deal-15",
    restaurant: "Pine Street Pizzeria",
    dealName: "Kids Slice Pack",
    price: 6.49,
    type: "Lunch",
    rating: 4.1,
    city: "Kearny",
    tags: ["kids", "value", "quick"],
    url: "https://example.com/pine-street-pizzeria",
    image: "https://placehold.co/600x400?text=Pine+Street+Pizzeria",
  },
];
